<a href="https://colab.research.google.com/github/RKayyy/ML_lab/blob/main/ML_Lab_Assignment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Q1

import numpy as np
arr = np.array([1,2,3,6,4,5])
np.flip(arr)

#flatten array
array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
array1.flatten()
array1.ravel()

#compare array
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])
np.array_equal(arr1, arr2)

#most frequent
x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
most_frequent_x = np.argmax(np.bincount(x))
most_frequent_y = np.argmax(np.bincount(y))
print(np.where(x == most_frequent_x)[0])
print(np.where(y == most_frequent_y)[0])

#sum of elements
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
#all elements
np.sum(gfg)
#row elements
np.sum(gfg,axis=1)
#column elements
np.sum(gfg,axis=0)

#sum continued
n_array = np.array([[55, 25, 15], [30, 44, 2], [11, 45, 77]])
#sum of diagonals
np.trace(n_array)
#eigen values
np.linalg.eig(n_array)
#eigen vectors
_, eigenvectors = np.linalg.eig(n_array)
print(eigenvectors)
#inverse of matrix
np.linalg.inv(n_array)
#determinant
np.linalg.det(n_array)

#multiplication and covariance
p = np.array([[1, 2], [2, 3]])
q = np.array([[4, 5], [6, 7]])
# Matrix multiplication
np.dot(p, q)
# Covariance between matrices
np.cov(np.dot(p, q))

#multiplication and covariance part b
p = [[1, 2], [2, 3], [4, 5]]
q = [[4, 5, 1], [6, 7, 2]]
#multiplication
np.dot(p,q)
#covariance
np.cov(np.dot(q,p))

#Products
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])
#Inner Product
np.inner(x, y)
#outer product
np.outer(x,y)
#cartesian product
np.array([(xi, yi) for xi in x for yi in y])



[0 5 7 8 9]
[0 1 2]
[[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]


array([[[ 2,  3,  4],
        [ 1,  5,  0]],

       [[ 2,  3,  4],
        [ 5, 10,  3]],

       [[ 3,  2,  9],
        [ 1,  5,  0]],

       [[ 3,  2,  9],
        [ 5, 10,  3]]])

In [ ]:
#Q2

#Numpy and Stats
array = np.array([[1, -2, 3], [-4, 5, -6]])
#Absolute value
np.abs(array)
#percentile
np.percentile(array, [25, 50, 75], axis=1)
np.percentile(array, [25, 50, 75], axis=0)
#Mean, median and std deviation
flattened_array = array.flatten()
np.mean(flattened_array)
np.median(flattened_array)
np.std(flattened_array)
#Mean, median and std deviation row wise
mean_column = np.mean(array, axis=0)
median_column = np.median(array, axis=0)
std_column = np.std(array, axis=0)
#Mean, median and std deviation column wise
mean_row = np.mean(array, axis=1)
median_row = np.median(array, axis=1)
std_row = np.std(array, axis=1)

#Floor,ceiling, truncated values
a = np.array([-1.8, -1.6, -0.5, 0.5, 1.6, 1.8, 3.0])
#floor values
np.floor(a)
#Ceiling values
np.ceil(a)
#truncated values
np.trunc(a)
#rounded values
np.round(a)

array([-2., -2., -0.,  0.,  2.,  2.,  3.])

In [ ]:
array = np.array([10,52,62,16,16,54,453])
sorted_array = np.sort(array)
print("Sorted array: ", sorted_array)

Sorted array:  [ 10  16  16  52  54  62 453]


In [ ]:
sorted_indices = np.argsort(array)
print("Indices: ", sorted_indices)

Indices:  [0 3 4 1 5 2 6]


In [ ]:
smallest4 = np.partition(array, 4)[:4]
print(smallest4)

[16 10 16 52]


In [ ]:
largest5 = np.partition(array, -5)[-5:]
print(largest5)

[ 16  52  62  54 453]


In [ ]:
#ques 3(b)

In [ ]:
array_b = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])
integer_elements_b = array_b[array_b.astype(int) == array_b]
print("Integer elements only:", integer_elements_b)

Integer elements only: [1. 2. 3. 2.]


In [ ]:
float_elements_b = array_b[array_b.astype(int) != array_b]
print("Float elements only:", float_elements_b)

Float elements only: [1.2 2.2]


In [ ]:
from google.colab import files

uploaded = files.upload()


Saving ameer-basheer-gV6taBJuBTk-unsplash.jpg to ameer-basheer-gV6taBJuBTk-unsplash.jpg


In [ ]:
# Assuming you uploaded an image named 'image.jpg'
image_path = list(uploaded.keys())[0]
print("Uploaded image path:", image_path)


Uploaded image path: ameer-basheer-gV6taBJuBTk-unsplash.jpg


In [ ]:
from PIL import Image

def img_to_array(path):
    image = Image.open(path)

    if image.mode == 'RGB':
        array = np.array(image)
        np.savetxt('image_rgb.txt', array.reshape(-1, 3), delimiter=' ', fmt='%d')
        print("RGB image saved as 'image_rgb.txt'")

    elif image.mode == 'L':
        array = np.array(image)
        np.savetxt('image_gray.txt', array, delimiter=' ', fmt='%d')
        print("Grayscale image saved as 'image_gray.txt'")

    else:
        print("Unsupported image mode:", image.mode)

# Usage example
img_to_array(image_path)


RGB image saved as 'image_rgb.txt'


In [ ]:
with open('image_rgb.txt', 'r') as file:
    contents = file.read()

print(contents)


IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



In [ ]:
import matplotlib.pyplot as plt

# Assuming the contents are space-separated integer values
data = np.loadtxt('image_rgb.txt')

# Reshape the data to the original image shape
image_shape = (data.shape[0], data.shape[1] // 3, 3)
image_data = data.reshape(image_shape).astype(np.uint8)

# Display the image
plt.imshow(image_data)
plt.axis('off')
plt.show()


In [ ]:
!sudo apt install tesseract-ocr

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  tesseract-ocr-eng tesseract-ocr-osd
The following NEW packages will be installed:
  tesseract-ocr tesseract-ocr-eng tesseract-ocr-osd
0 upgraded, 3 newly installed, 0 to remove and 16 not upgraded.
Need to get 4,816 kB of archives.
After this operation, 15.6 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy/universe amd64 tesseract-ocr-eng all 1:4.00~git30-7274cfa-1.1 [1,591 kB]
Get:2 http://archive.ubuntu.com/ubuntu jammy/universe amd64 tesseract-ocr-osd all 1:4.00~git30-7274cfa-1.1 [2,990 kB]
Get:3 http://archive.ubuntu.com/ubuntu jammy/universe amd64 tesseract-ocr amd64 4.1.1-2.1build1 [236 kB]
Fetched 4,816 kB in 3s (1,926 kB/s)
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debc

In [ ]:
!pip install pytesseract

In [ ]:
import pytesseract
import shutil
import os
import random

In [ ]:
try:
 from PIL import Image
except ImportError:
 import Image

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving Backslash headingS.png to Backslash headingS.png


In [ ]:
from google.colab import files
uploaded = files.upload()

Saving BCSHEADINGNEW.png to BCSHEADINGNEW.png


In [ ]:
image_path_in_colab='BCSHEADINGNEW.png'
extractedInformation = pytesseract.image_to_string(Image.open(image_path_in_colab))
print(extractedInformation)

In [ ]:
print(pytesseract.image_to_boxes(Image.open(image_path_in_colab)))

~ 48 224 1775 450 0



In [ ]:
import json
import os

from google.colab import files

In [ ]:
license_keys = files.upload()
os.rename(list(license_keys.keys())[0], 'spark_ocr.json')

with open('spark_ocr.json') as f:
    license_keys = json.load(f)

# Defining license key-value pairs as local variables
locals().update(license_keys)

Saving BCSHEADINGNEW.png to BCSHEADINGNEW (1).png


UnicodeDecodeError: ignored

In [ ]:
# Installing pyspark and spark-nlp
! pip install --upgrade -q pyspark==3.0.2 spark-nlp==$PUBLIC_VERSION

# Installing Spark OCR
! pip install spark-ocr==$OCR_VERSION\+spark30 --extra-index-url=https://pypi.johnsnowlabs.com/$SPARK_OCR_SECRET --upgrade

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 204.8/204.8 MB 3.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
ERROR: Could not find a version that satisfies the requirement spark-nlp== (from versions: 1.6.2, 1.6.3, 1.7.0, 1.7.1, 1.7.2, 1.7.3, 1.8.0, 1.8.1, 1.8.2, 1.8.3, 1.8.4, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6, 2.0.7, 2.0.8, 2.0.9, 2.1.0rc1, 2.1.0rc2, 2.1.0, 2.1.1, 2.2.0rc1, 2.2.0rc2, 2.2.0rc3, 2.2.0, 2.2.1, 2.2.2, 2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.3.4, 2.3.5, 2.3.6, 2.4.0rc1, 2.4.0, 2.4.1, 2.4.2, 2.4.3, 2.4.4rc1, 2.4.4, 2.4.5, 2.5.0rc1, 2.5.0rc2, 2.5.0, 2.5.1, 2.5.2, 2.5.3, 2.5.4, 2.5.5, 2.6.0rc1, 2.6.0rc2, 2.6.0rc3, 2.6.0, 2.6.1, 2.6.2, 2.6.3rc1, 2.6.3rc2, 2.6.3rc3, 2.6.3, 2.6.4, 2.6.5, 2.7.0rc1, 2.7.0, 2.7.0.post1, 2.7.1, 2.7.2, 2.7.3, 2.7.4, 2.7.5, 3.0.0rc1, 3.0.0rc2, 3.0.0rc3, 3.0.0rc7, 3.0.0rc8, 3.0.0rc10, 3.0.0rc11, 3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.1.0, 3.1.1, 3.1.2, 3.1.3, 3.2.0, 3.2.1, 3.2.2, 3.2.3, 3.3.0, 3.3.1, 3.3.2, 3.3.3, 3.3.4, 3.4.0rc1, 3.4.0, 3.4.1, 

In [ ]:
!sudo apt install tesseract-ocr

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
tesseract-ocr is already the newest version (4.1.1-2.1build1).
0 upgraded, 0 newly installed, 0 to remove and 16 not upgraded.


In [ ]:
import pytesseract

import shutil

import os

import random

try:

  from PIL import Image

except ImportError:

  import Image

In [ ]:
from google.colab import files

uploaded = files.upload()


Saving left.png to left.png


In [ ]:
image_path_in_colab='left.png'

extractedInformation = pytesseract.image_to_string(Image.open(image_path_in_colab))


In [ ]:
print(extractedInformation)

LEFT

